version: '3.7'
services:
    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            - redis

    redis-insight:
        image: redislabs/redisinsight
        ports:
            - 8001:8001
        networks:
            - redis
    db:
        container_name: db
        image: mariadb
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        networks:
            - db

    php-swoole-websocket:
        container_name: php-swoole-websocket
        build: ./php-swoole
        ports:
            - 9502:9502
        volumes:
            - ./server:/var/www:cached
        depends_on:
            - db
        environment:
            MODE: "WEBSOCKET"
        networks:
            - db
            - redis

    php-swoole-tick-server:
        build: ./php-swoole
        volumes:
            - ./server:/var/www:cached
        depends_on:
            - db
            - redis
        environment:
            AUTORELOAD_PROGRAMS: "swoole"
            AUTORELOAD_ANY_FILES: 1
            MODE: "TICK_SERVER"
        networks:
            - db
            - redis

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./php-fpm/nginx.conf:/etc/nginx/conf.d/site.conf
            - ./server:/var/www
        networks:
            - php

    php:
        build: ./php-fpm
        volumes:
            - ./server:/var/www
        networks:
            - db
            - php

networks:
    db:
    php:
    redis:
