ping:
    path: /ping
    controller: App\Controller\PingController::index

move:
    path: /move
    controller: App\Controller\MovementController::index

jump:
    path: /jump
    controller: App\Controller\JumpController::index

schema:
    path: /schema
    controller: App\Controller\JsonSchemaTest::index
