ping:
    path: /ping
    controller: App\Controller\PingController::index

move:
    path: /move
    controller: App\Controller\MovementController::index
    defaults:
        _schema: 'move.json'

jump:
    path: /jump
    controller: App\Controller\JumpController::index
    defaults:
        _schema: 'jump.json'
