services:
    _defaults:
        public: true

    test.App\DataFixtures\UserFixtures: '@App\DataFixtures\UserFixtures'
    test.App\DataFixtures\ShipFixtures: '@App\DataFixtures\ShipFixtures'
    test.App\DataFixtures\JumpNodeFixtures: '@App\DataFixtures\JumpNodeFixtures'
    test.App\DataFixtures\Economy\CommodityFixtures: '@App\DataFixtures\Economy\CommodityFixtures'
    test.App\DataFixtures\DockableFixtures: '@App\DataFixtures\DockableFixtures'

    test.App\Service\Manipulators\StorageManipulatorService: '@App\Service\Manipulators\StorageManipulatorService'

