name: PHP Composer

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
      APP_ENV: test

    steps:
      - uses: actions/checkout@v2
      - uses: docker://karljacques/spaceface-test-container:lastest
      
      - name: Validate composer.json and composer.lock
        run: composer validate
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ${{env.working-directory}}

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Initialise test database
        run: php bin/console doctrine:schema:create --env=test
        working-directory: ${{env.working-directory}}

      - name: Run test suite
        run: php bin/phpunit --configuration phpunit.xml.dist tests --teamcity
        working-directory: ${{env.working-directory}}

