name: Server

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: karljacques/spaceface-test-container:latest
    env:
      working-directory: ./server
      APP_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ${{env.working-directory}}

      - name: Upload Vendor Artifacts
        uses: actions/upload-artifact@v1
        working-directory: ${{env.working-directory}}
        with:
          name: vendor
          path: ./vendor

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
      - name: Initialise test database
        run: php bin/console doctrine:schema:create --env=test
        working-directory: ${{env.working-directory}}


  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    container: karljacques/spaceface-test-container:latest
    env:
      working-directory: ./server
      APP_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: vendor

      - name: Run Unit Tests
        run: php bin/phpunit --configuration phpunit.xml.dist tests/Unit --teamcity
        working-directory: ${{env.working-directory}}

